# Generated by Django 2.1.3 on 2018-12-26 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_auto_20181226_2212'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project Name:')),
                ('description', models.CharField(max_length=100, verbose_name='Short Description:')),
                ('price_type', models.CharField(choices=[('bill', 'Billable'), ('non_bill', 'Non-billable'), ('fixed', 'Fixed price')], default='bill', max_length=10, verbose_name='Project Price Type:')),
                ('budgetted_hours', models.FloatField(blank=True, default=0.0, null=True)),
                ('kind', models.CharField(choices=[('single', 'Single'), ('going', 'Ongoing')], default='single', max_length=10, verbose_name='Single/Ongoing:')),
                ('fixed_price_currency', models.CharField(blank=True, default='', max_length=3)),
                ('fixed_price', models.FloatField()),
                ('fixed_hours', models.CharField(default='', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name="Who's the client?")),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee', verbose_name='Project manager:')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProjectPhase', verbose_name='Project phase:'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ProjectState', verbose_name='Project state:'),
        ),
    ]
