# Generated by Django 2.1.3 on 2018-12-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_ref_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Client reference number (CRN):'),
        ),
        migrations.AddField(
            model_name='project',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Invoice number (IRN):'),
        ),
    ]
