# Generated by Django 2.1.3 on 2018-12-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181226_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fixed_price',
            field=models.FloatField(default=0),
        ),
    ]
