# Generated by Django 2.1.3 on 2018-12-17 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobtitles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, verbose_name='Address:')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State/Province:')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='Zip/Postal Code:')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City/Town:')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin Role ?')),
                ('picture', models.ImageField(blank=True, upload_to='photos/employees/%Y/%m/%d', verbose_name='Photo:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobtitles.JobTitle')),
            ],
        ),
    ]
