# Generated by Django 2.1.3 on 2018-12-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('charge_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Charge per hour:')),
                ('sold_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Sold per hour:')),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=2, verbose_name='VAT:')),
                ('skill_level', models.CharField(choices=[('', '-- (Select level)--'), ('low', 'Low'), ('high', 'High'), ('inter', 'Intermediate')], default='', max_length=10, verbose_name='Skill level:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
