# Generated by Django 2.1.3 on 2019-02-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('activities', '0004_activity_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='departments',
        ),
        migrations.AddField(
            model_name='activity',
            name='department',
            field=models.ManyToManyField(blank=True, to='departments.Department'),
        ),
    ]
