# Generated by Django 2.1.3 on 2019-02-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20190202_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='VAT:'),
        ),
    ]
