# Generated by Django 2.1.3 on 2019-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20190203_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='charge_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, null=True, verbose_name='charge per hour:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sold_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=5, null=True, verbose_name='sold per hour:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='VAT:'),
        ),
    ]
