# Generated by Django 2.1.3 on 2018-12-26 17:56

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Full Company Name:')),
                ('name', models.CharField(max_length=30, verbose_name='Name (for internal use))')),
                ('vat_number', models.CharField(max_length=100, verbose_name='VAT Number:')),
                ('address', models.TextField(blank=True, verbose_name='Address:')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='State/Province:')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='Zip/Postal Code:')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City/Town:')),
                ('country', django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='Country:')),
                ('inv_tpl', models.CharField(choices=[('EUR', 'EUR'), ('US', 'US'), ('OTHER', 'OTHER')], default='EUR', max_length=5, verbose_name='Invoice Template:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
